package logic.utils;

public enum NotificationTypes {
    USER_REGISTRATION,
    EVENT_ADDED,
    EVENT_DELETED,
    USER_EVENT_PARTICIPATION,
    USER_EVENT_REMOVAL,
    CHANGE_CITY,
    LOGGED_IN,
    DISCONNECTED,
    GROUP_JOIN,
    GROUP_LEAVE,
}
